### PR TITLE
Magic Notes Added

### PR DESCRIPTION
**Pull request by Adityamishra9719**
I had added a Notes Site named as  Magic Notes
It is a React app
There are two fields the title field and the message field and a add button using it you can add the note
There is delete button for deleting the notes.
Issue #400 

It looks like the below screen shot :-

**Screenshots **
Screenshot 2023-07-02 204239

**Working Video**

https://github.com/Vikash-8090-Yadav/Future.WebNet/assets/105539123/8196468c-1998-42ab-a88c-12485bd24d2d

My branch name is Adityamishra9719
Thank you.

### CODE REVIEW

**Comment by shubhisingh184** [comment]
@Adityamishra9719 please attach working video here and its link in README.md file.

**Comment by Adityamishra9719** [comment]
Working video added Successfully!

**Comment by shubhisingh184** [comment]
@Adityamishra9719 This issue is only for magic notes, but there is also snake game folder present. Remove that folder, so that this pull request will get merged, Okay!

**Comment by Adityamishra9719** [comment]
Okk

**Comment by Adityamishra9719** [comment]
there is an issue in pr

**Pull request closed without merging**
