### PR TITLE
Super Burger Landpage issue no. #248

### PR DESCRIPTION
**Pull request by Shu12388y**
[Screencast from 06-07-23 08:10:41 PM IST.webm](https://github.com/Vikash-8090-Yadav/Future.WebNet/assets/91714143/a273afa5-5f23-4cfd-842a-542146d72e9d)

# Super Burger landing page  Issue no. #248 

I have added the files and folders.Please check and review

### CODE REVIEW

**Review by shubhisingh184 — APPROVED** [review]

**Comment by Vikash-8090-Yadav** [comment]
Please delete the node_moduless folder or make it under the .gitignore. Uploading this in Github is not good practice. Thanks!

**Comment by Shu12388y** [comment]
@Vikash-8090-Yadav  I will remove the node module folder by today

**Comment by Shu12388y** [comment]
@Vikash-8090-Yadav I have removed the node module folder

**Comment by shubhisingh184** [comment]
@Vikash-8090-Yadav please have a look.

**Review by Vikash-8090-Yadav — APPROVED** [review]
LGTM

**Pull request merged**
