### PR TITLE
Random Password Generator (#357)

### PR DESCRIPTION
**Pull request by Tusharjoshi1703**
Working video

https://github.com/Vikash-8090-Yadav/Future.WebNet/assets/103979298/67d2fad2-8308-48e9-9040-2f6265290fc1

### CODE REVIEW

**Comment by shubhisingh184** [comment]
@Tusharjoshi1703 From the next time, name the file as README.md not readme.md, that is the proper way. Okay!

**Review by shubhisingh184 — APPROVED** [review]

**Comment by Tusharjoshi1703** [comment]
Okay I'll follow that!

**Comment by Tusharjoshi1703** [comment]
Hey can you please merge it into main as I am ready with my next pr

**Comment by Tusharjoshi1703** [comment]
@shubhisingh184  Can You please merge it into main ?

**Review by Vikash-8090-Yadav — APPROVED** [review]
LGTM

**Pull request merged**
