### PR TITLE
Bucket_List is added

### PR DESCRIPTION
**Pull request by TanyaNegi10**
# Description📜

The project Bucket_list using HTML, CSS , SASS , Flexbox is completed.
Fixes:  Bucket_list #401

# Type of Change 📝
- Add a new project

# Domain of Contribution 📊
- Project using only HTML ,CSS , SASS, Flexbox 

I'm SSOC'23 Contributor

Bucketpage1

Bucketpage2

Bucketpage3

### CODE REVIEW

**Comment by shubhisingh184** [comment]
@TanyaNegi10 In your project folder there's no files in it, please check it once again. Please upload the working video of your project in README.md file and also here in conversation section.

**Comment by TanyaNegi10** [comment]
@shubhisingh184 plss check now

**Comment by shubhisingh184** [comment]
@TanyaNegi10 there's a submodule in Front-end Projects, that needs to be removed in order to merge this pr. Do this ASAP.

**Comment by TanyaNegi10** [comment]
@shubhisingh184 I've removed the submodule can u plss check now

**Comment by shubhisingh184** [comment]
@TanyaNegi10 please remove node modules from your folder, it's not a good practice to upload that on GitHub. Do this ASAP,and let me know so we can merge this pull request.

**Comment by TanyaNegi10** [comment]
@shubhisingh184 plss check now

**Comment by shubhisingh184** [comment]
@TanyaNegi10 please update or sync your branch as in your files changed there is a folder of music shop, that shouldn't be there. Please sync and fetch, let me know when you're done.

**Comment by shubhisingh184** [comment]
@TanyaNegi10 dm me on discord immediately.

**Review by shubhisingh184 — APPROVED** [review]

**Pull request merged**
