### PR TITLE
Chat Web Application

### LINKED ISSUE #313: Chatting Web Application
# Project title
Chatting Web Application

### Project Description
This is a web application like Chatting clone.
Which is also responsive made by (HTML, CSS, Js (vanilla js))

### Doc Domain

- [] Solidity , Html, Css , JavaScript , Web3.js / Ether.js
- [] Solidity , ReactJs /NextJs , Web3.js /Ether.js
- [] Solidity , Python3 , Web3.py
- [] Other , feel free to mention below

#### Are you contributing under any open-source program ? Yes
image

<hr/>

### PR DESCRIPTION
**Pull request by TanishqSiva**
closes #313 
Kindly review it as it is my most complicated project i've ever made. Please merge it after the review

### CODE REVIEW

**Comment by TanishqSiva** [comment]
added everything this PR is ready to get merged

**Comment by Vikash-8090-Yadav** [comment]
WHy you are pusing all the file to the same folder make different folder under frontend directory and push them there. Thanks!

**Comment by TanishqSiva** [comment]
even this is resolved please check

**Comment by Vikash-8090-Yadav** [comment]
Hey bro still same. If possible mesage in the discord channel made for  this project

**Comment by Vikash-8090-Yadav** [comment]
Change the readme name from README.md

**Comment by shubhisingh184** [comment]
@TanishqSiva  If you want to contribute your project under SSOC'23 then you should complete it ASAP. Please create a README.md file in your project and attach working video in README.md file and also in conversation section.

**Pull request closed without merging**
