### PR TITLE
Car racing game

### PR DESCRIPTION
**Pull request by NupurHardiya**
Experience the excitement of a game crafted with HTML, CSS, and JavaScript. Engage in thrilling gameplay, navigate through visually stunning environments. Immerse yourself in this captivating adventure today!

### CODE REVIEW

**Comment by Vikash-8090-Yadav** [comment]
Issue NO?

**Comment by Vikash-8090-Yadav** [comment]
Hey please check Your pr is empty. Thanks!

**Comment by NupurHardiya** [comment]
> 

I added a zip file.

**Comment by Vikash-8090-Yadav** [comment]
Hey please don't add a zip file. Follow the guidelines. Thanks!

**Pull request closed without merging**
