### PR TITLE
Myntra Clone 

### PR DESCRIPTION
**Pull request by ayan-joshi**
As I explained in the Issue , I added the Myntra Clone to the frontend projects section with a proper readme file explaining the project.
Please merge my pull request 
I'm a SSOC contributor.

### CODE REVIEW

**Comment by Vikash-8090-Yadav** [comment]
Issue No ?

**Comment by ayan-joshi** [comment]
Issue no 283 @Vikash-8090-Yadav

**Comment by ayan-joshi** [comment]
@Vikash-8090-Yadav please look out and merge the request

**Comment by ayan-joshi** [comment]
@Vikash-8090-Yadav sir please merge the request

**Comment by Vikash-8090-Yadav** [comment]
Thanks!

**Pull request merged**
