### PR TITLE
Improved Marketplace File

### PR DESCRIPTION
**Pull request by ayan-joshi**
As explained in the issue #319 
Improved the alignment of the file , button 
improved the text css of the sentences of buyer and owner options 
added a preferable background colour 

Screenshot (186)

Please merge my request @Vikash-8090-Yadav

### CODE REVIEW

**Comment by Vikash-8090-Yadav** [comment]
PLease atatch the running  video in the PR.

**Comment by ayan-joshi** [comment]
> PLease atatch the running video in the PR.

demo video ?

**Comment by shubhisingh184** [comment]
@ayan-joshi yes, attach a demo video of your changes.

**Comment by shubhisingh184** [comment]
@ayan-joshi are you working on this ?

**Comment by ayan-joshi** [comment]
> @ayan-joshi are you working on this ?

I worked on it , changed the colour and align the items

**Comment by shubhisingh184** [comment]
@ayan-joshi can you attach working video of your changes in that project ?

**Comment by ayan-joshi** [comment]
> @ayan-joshi can you attach working video of your changes in that project ?

ma'am there are very minimal changes like bg color changes and alignment of the file that would have been seen on the commit itself please can it be merged without video ?

**Comment by shubhisingh184** [comment]
@ayan-joshi This is actually a rule here to proof that the changes are working well and if you don't follow these rules, then everyone will say the same thing. So, it would be better if you make a small video and attach here, that will not take more than 5 minutes. I hope you'll understand this.

**Pull request closed without merging**
