### PR TITLE
Bingo Game Completed [SSoC'23 2.0]

### PR DESCRIPTION
**Pull request by Avdhesh-Varshney**
Title - Bingo Game
Type - Frontend Project
Technology used - HTML, CSS and JS
Completed issue number - #265 

- This game is like a magnetic force, pulling you in effortlessly and capturing your heart. And guess what? 
- Adding some background music to the mix takes the excitement to a whole new level. 
- When you win the game, it's like a burst of joy that makes you want to keep playing and savoring every moment. 
- Congratulations on your victory! You're in for a treat as you dive deeper into this game that will warm your heart and leave you wanting more. 

Get ready to be swept away in a world of pure delight!

### CODE REVIEW

**Comment by Vikash-8090-Yadav** [comment]
Issue No ?

**Comment by Avdhesh-Varshney** [comment]
@Vikash-8090-Yadav Sir, I have done with my pull request of Bingo Game.
Please Merge it into the main branch and update my quine points.

**Comment by Vikash-8090-Yadav** [comment]
Your  images are not loading, plese chk once

**Comment by Vikash-8090-Yadav** [comment]
Tag me once done. Thanks !

**Comment by Avdhesh-Varshney** [comment]
@Vikash-8090-Yadav Sir, please again **review** my pull request and update the points of quine.

**Comment by Vikash-8090-Yadav** [comment]
Thanks @Avdhesh-Varshney . Regarding quine msg on the discord future.webnet channel.

**Pull request merged**
