### PR TITLE
Added CodePen clone project

### PR DESCRIPTION
**Pull request by Vidip-Ghosh**
I have added a project CodePen Clone which is used for testing HTML, CSS and JS Code using React JS and Material UI.
Closes Issue #292

### CODE REVIEW

**Comment by Vikash-8090-Yadav** [comment]
Noting is visible in this Pr.PLease chk once

**Comment by Vidip-Ghosh** [comment]
> Noting is visible in this Pr.PLease chk once

@Vikash-8090-Yadav now check if everything is alright?

**Comment by Vikash-8090-Yadav** [comment]
Make the perfect readme, for reference check the frontend folder.

**Comment by Vikash-8090-Yadav** [comment]
There's nothing in readme check once.

**Comment by Vidip-Ghosh** [comment]
@Vikash-8090-Yadav now please check is readme visible or not?

**Comment by Vidip-Ghosh** [comment]
Sorry, I couldn't make readme since I found that the text cursor gets disappear after every character. So, now closing this PR.

**Pull request closed without merging**
