### PR TITLE
PR for Payment form SSOC'23 #291

### PR DESCRIPTION
**Pull request by Venerablevivek**
I have Added payment form in the directory. Please merge this PR

### CODE REVIEW

**Comment by Venerablevivek** [comment]
@Vikash-8090-Yadav check this PR

**Comment by shubhisingh184** [comment]
@Venerablevivek please create a README.md file in your project and attach working video of your project in that file and here in conversation section too.

**Comment by shubhisingh184** [comment]
@Venerablevivek If you want to contribute your project under SSOC'23 then you should complete it ASAP.

**Comment by Vikash-8090-Yadav** [comment]
@Venerablevivek issue number bro?

**Comment by shubhisingh184** [comment]
@Venerablevivek If you want to contribute under SSOC'23, then complete it ASAP.

**Pull request closed without merging**
