### PR TITLE
Update TaskContract.sol

### PR DESCRIPTION
**Pull request by AVI-SHUKLA1110**
### Bound Check for array input.
+ In the getMyTasks function, there is no bounds checking when copying tasks into the temporary array. If the counter exceeds the temporary array's length, it could lead to an exception. We can add a check to ensure counter doesn't exceed temporary's length.

### So , I updated the file with required changes.

### CODE REVIEW

**Comment by shubhisingh184** [comment]
@AVI-SHUKLA1110 what is your issue no.?

**Comment by shubhisingh184** [comment]
@AVI-SHUKLA1110 then you should create an issue first and when it'll get assigned to you, then raise a pull request okay.

**Comment by AVI-SHUKLA1110** [comment]
Okayy thnks

**Comment by AVI-SHUKLA1110** [comment]
@shubhisingh184  the issue number is https://github.com/Vikash-8090-Yadav/Future.WebNet/issues/503

**Comment by AVI-SHUKLA1110** [comment]
@Vikash-8090-Yadav  @shubhisingh184  please merge it

**Review by Vikash-8090-Yadav — APPROVED** [review]
LGTM

**Pull request merged**
