### PR TITLE
[SSoC 2.0] Music Studio Game Completed

### PR DESCRIPTION
**Pull request by Avdhesh-Varshney**
Title - Music Studio Game
Issue Number - 435

close issue #435 

<br>

Screenshot 

<br>

image

### CODE REVIEW

**Comment by Avdhesh-Varshney** [comment]
@Vikash-8090-Yadav @shubhisingh184 sir, please review this pull request

**Comment by shubhisingh184** [comment]
@Avdhesh-Varshney please attach the working video of your project in README.md file and here in conversation section too.

**Comment by Avdhesh-Varshney** [comment]
@shubhisingh184 @Vikash-8090-Yadav sir, please again review this pr

Working video

<br>

https://github.com/Vikash-8090-Yadav/Future.WebNet/assets/114330097/9aa90c71-e02f-411c-8400-ebc4839c7257

**Review by shubhisingh184 — APPROVED** [review]

**Review by Vikash-8090-Yadav — APPROVED** [review]
LGTM

**Pull request merged**
