### PR TITLE
netflix Added

### PR DESCRIPTION
**Pull request by dontwike**

### CODE REVIEW

**Comment by dontwike** [comment]
I was assigned issue number #310. I have added my work.

**Comment by Vikash-8090-Yadav** [comment]
Readme.md not created please   make this .

**Comment by dontwike** [comment]
Okay I will create the README.md file

**Comment by dontwike** [comment]
I have added Readme.md file

**Comment by shubhisingh184** [comment]
@dontwike please attach working video in README.md file and here in conversation section too.

**Comment by dontwike** [comment]
I have added the video

**Comment by shubhisingh184** [comment]
@dontwike please upload the working video in README.md file only not in the folder of your project and also attach that working video in conversation section.

**Comment by dontwike** [comment]
https://github.com/Vikash-8090-Yadav/Future.WebNet/assets/100211916/78881e60-faf5-4399-846a-c9052cfd95c7

Here it is

**Comment by shubhisingh184** [comment]
@dontwike please make 2 changes:
1. Remove the mp4 video from your folder as it will increase the size of your project ( as we have working video in your project inside the README.md file so no need to put that video separately in your folder).
2. Please rename your project name to Netflix_Landing_Page.
Kindly do these mentioned changes.

**Comment by dontwike** [comment]
Done

**Review by shubhisingh184 — APPROVED** [review]

**Comment by dontwike** [comment]
Is there anything for me to do

**Comment by shubhisingh184** [comment]
> Is there anything for me to do

No, when it'll get approved by PA, then it'll get merged. So, don't worry. Okay!

**Pull request merged**
