### PR TITLE
Lucky Die game Added 

### PR DESCRIPTION
**Pull request by ayan-joshi**
As described in the issue #425 
Added the Dice Game , included the Readme file with the proper 
explanation.
here is the demo video in the conversation :

https://github.com/Vikash-8090-Yadav/Future.WebNet/assets/96243602/091b7daf-dcfc-41a5-bec0-0b636bb313e7

I'm a SSOC contributor , please merge my request @shubhisingh184 @Vikash-8090-Yadav

### CODE REVIEW

**Comment by ayan-joshi** [comment]
> @ayan-joshi please upload the demo video again as it's not uploaded correctly.

Sorry for the previous mistake , I did it now

**Comment by shubhisingh184** [comment]
@ayan-joshi please also attach demo video correctly in README.md file

**Comment by ayan-joshi** [comment]
> @ayan-joshi please also attach demo video correctly in README.md file

did it aswell

**Comment by shubhisingh184** [comment]
@ayan-joshi still the video isn't properly attached in README.md file. Please check it and upload it properly.

**Comment by ayan-joshi** [comment]
> @ayan-joshi still the video isn't properly attached in README.md file. Please check it and upload it properly.

did the change and I can view the video in the readme and I have also added the video in the project file also

**Comment by shubhisingh184** [comment]
@ayan-joshi the working video is not properly uploaded in README.md file yet, it's on the code part but when you preview it, it doesn't appear. Please check it once carefully.

**Comment by shubhisingh184** [comment]
@ayan-joshi if you want to contribute in SSOC'23, then you should complete it ASAP.

**Comment by ayan-joshi** [comment]
@shubhisingh184 now it's done probably done

**Comment by shubhisingh184** [comment]
@ayan-joshi now it seems fine to me.

**Review by shubhisingh184 — APPROVED** [review]

**Pull request merged**
