### PR TITLE
created weather app

### PR DESCRIPTION
**Pull request by Tusharjoshi1703**
#234 done 
tech stack used 
[x]-Html ,css ,javascript

### CODE REVIEW

**Comment by SahuAshutosh** [comment]
This app is nice work

**Comment by Vikash-8090-Yadav** [comment]
Thanks @Tusharjoshi1703

**Comment by Tusharjoshi1703** [comment]
Is my pr merged??

**Comment by Tusharjoshi1703** [comment]
Your most welcome☺️

**Comment by Tusharjoshi1703** [comment]
also completed #235 please check as it got merged with #234
completed zomato clone i.e #235 
tech stack used  html ,css and javascript
please check

**Pull request merged**
