### PR TITLE
Music shop

### PR DESCRIPTION
**Pull request by Shu12388y**
Music Shop webpage #301

### CODE REVIEW

**Comment by Vikash-8090-Yadav** [comment]
Please create the readme.md

**Comment by shubhisingh184** [comment]
@Shu12388y Please add README.md file in your project and follow the contributions.md guidelines. In case you're facing any problem, let me know, Okay!

**Comment by Shu12388y** [comment]
@Vikash-8090-Yadav @shubhisingh184 I have added the readme file. Please check.
Thank you

**Comment by shubhisingh184** [comment]
@Shu12388y please create a separate README.md file that follows contributions.md guidelines format and attach working video of you project. If you're facing any problem, then DM me on discord, I'll help you out. Hope it helps!

**Comment by Shu12388y** [comment]
[Screencast from 04-07-23 08:50:38 PM IST.webm](https://github.com/Vikash-8090-Yadav/Future.WebNet/assets/91714143/cbc269fe-68f5-451b-9534-9344c8749b1e)

**Review by shubhisingh184 — APPROVED** [review]

**Comment by Vikash-8090-Yadav** [comment]
@Shu12388y  I guess the video is not loaded correctly and instead of pasting the video hyperlinks, please upload the full running video in the readme only. Thanks!. Please check once and update me or @shubhisingh184. Thanks!

**Comment by shubhisingh184** [comment]
Okay, I'll update you.

**Comment by Shu12388y** [comment]
@Vikash-8090-Yadav @shubhisingh184 I have added the image and video in the readme file

**Pull request closed without merging**
