### PR TITLE
Image Slider #359

### PR DESCRIPTION
**Pull request by Tusharjoshi1703**
imageslider

https://github.com/Vikash-8090-Yadav/Future.WebNet/assets/103979298/845af521-4104-464c-bf46-07997cfd208a

### CODE REVIEW

**Comment by shubhisingh184** [comment]
@Tusharjoshi1703 please mention issue number.

**Comment by Tusharjoshi1703** [comment]
#359 Done. Sorry I forgot to add issue number.

**Comment by Tusharjoshi1703** [comment]
@shubhisingh184 I have added the issue number. Please have a look.

**Review by shubhisingh184 — APPROVED** [review]

**Comment by Tusharjoshi1703** [comment]
@shubhisingh184  Can you merge it as my next project is ready?

**Review by Vikash-8090-Yadav — APPROVED** [review]
LGTM

**Comment by Tusharjoshi1703** [comment]
Thanks for merging it into main 👍

**Pull request merged**
