### PR TITLE
Car Racing Game

### PR DESCRIPTION
**Pull request by NupurHardiya**
Experience the excitement of a game crafted with HTML, CSS, and JavaScript. Engage in thrilling gameplay, navigate through visually stunning environments. Immerse yourself in this captivating adventure today!
[Issue no. - #243]

### CODE REVIEW

**Comment by shubhisingh184** [comment]
@NupurHardiya please attach working video and screenshot of your project here and also create a README.md file for your project. Please go through the contributions.md guidelines first.

**Comment by shubhisingh184** [comment]
@NupurHardiya still there's no screenshot and working video link in README.md file and also attach the working video here in conversation section, then you're good to go.

**Comment by NupurHardiya** [comment]
https://github.com/Vikash-8090-Yadav/Future.WebNet/assets/113535580/2fb17f60-28ab-4eeb-9cb5-5ab92ad68951

**Review by Vikash-8090-Yadav — APPROVED** [review]
LGTM

**Pull request merged**
