### PR TITLE
[SSoC 2.0] Time Watcher Project Ready

### PR DESCRIPTION
**Pull request by Avdhesh-Varshney**
Title - Time Watcher
Tech used - HTML, CSS and JS
Issue Number - 380

close issue #380 

Screenshot of the project

<br>

image

### CODE REVIEW

**Comment by Avdhesh-Varshney** [comment]
@Vikash-8090-Yadav @shubhisingh184 Sirs, please review this pr and requested to merge for a successful contribution under SSoC 2.0 program

**Comment by shubhisingh184** [comment]
@Avdhesh-Varshney please attach working video link in README.md file and also here  in conversation section.

**Comment by Avdhesh-Varshney** [comment]
@Vikash-8090-Yadav @shubhisingh184 Sir, please again review this pr

Demo Video:

https://github.com/Vikash-8090-Yadav/Future.WebNet/assets/114330097/521ca845-a97b-4ffe-95cc-674db68a9bad

**Review by shubhisingh184 — APPROVED** [review]

**Review by Vikash-8090-Yadav — APPROVED** [review]
LGTM

**Pull request merged**
