### PR TITLE
[SSoC 2.0] Large Factorial Calculator Ready

### LINKED ISSUE #403: [SSoC 2.0] Large Factorial Generator Project
### Project title
(Write project title over here)
Title - Factorial Calculator
Tech using - HTML, CSS and JS

### Project Description
(Describe the project over here)
- Front-end Project
- Card and colouring effect to attract users
- Animated effects
- Enter the number, project will return the factorial of that entered number instantly

### Doc Domain

- [x] Solidity , Html, Css , JavaScript , Web3.js / Ether.js
- [] Solidity , ReactJs /NextJs , Web3.js /Ether.js
- [] Solidity , Python3 , Web3.py
- [] Other , feel free to mention below

#### Are you contributing under any open-source program ?
Yes, SSoC 2.0 program
<hr/>

### PR DESCRIPTION
**Pull request by Avdhesh-Varshney**
Title - Large Factorial Calculator
Issue Number - 403

Closes #403 

<br>

Demo Video

<br>

https://github.com/Vikash-8090-Yadav/Future.WebNet/assets/114330097/a91e9701-be68-4316-84b5-3724af394eec

### CODE REVIEW

**Comment by Avdhesh-Varshney** [comment]
@Vikash-8090-Yadav @shubhisingh184 please review this pull request

**Comment by shubhisingh184** [comment]
@Avdhesh-Varshney This project is working fine, but one piece of advice for you from my side, if you're working on small projects to learn, then you can create much more attractive UI for your project. Okay !

**Review by shubhisingh184 — APPROVED** [review]

**Comment by Avdhesh-Varshney** [comment]
> @Avdhesh-Varshney This project is working fine, but one piece of advice for you from my side, if you're working on small projects to learn, then you can create much more attractive UI for your project. Okay !

@shubhisingh184 ma'am please review the new look of the website

image

Is it better ?

**Comment by shubhisingh184** [comment]
> > @Avdhesh-Varshney This project is working fine, but one piece of advice for you from my side, if you're working on small projects to learn, then you can create much more attractive UI for your project. Okay !
> 
> @shubhisingh184 ma'am please review the new look of the website
> 
> image
> 
> Is it better ?

yeah, now it looks a lot better. Thankyou for your efforts. I really appreciate it.

**Pull request merged**
