### PR TITLE
Amazon clone

### LINKED ISSUE #308: Amazon Clone
Project title
Amazon Clone

Project Description
This is an E-COMMERCE website, tech stack to used is HTML, CSS, Js

Doc Domain

- [] Solidity , Html, Css , JavaScript , Web3.js / Ether.js
- [] Solidity , ReactJs /NextJs , Web3.js /Ether.js
- [] Solidity , Python3 , Web3.py
- [] Other , feel free to mention below

#### Are you contributing under any open-source program ? Yes
Amazon clone
<hr/>

### PR DESCRIPTION
**Pull request by TanishqSiva**
closes #308 
Kindly review it and then merge it
there were some bugs in previous branch so i closed it and openend new one please check this @Vikash-8090-Yadav sir as soon possible
is the conflict resolved please check

### CODE REVIEW

**Comment by TanishqSiva** [comment]
Need some guidance to resolve @Vikash-8090-Yadav

**Comment by TanishqSiva** [comment]
It has been resolved please check

**Comment by Vikash-8090-Yadav** [comment]
This is not the amazon clone chk readme again

**Comment by TanishqSiva** [comment]
> This is not the amazon clone chk readme again

no it is changed check it once

**Comment by Vikash-8090-Yadav** [comment]
@TanishqSiva still the same issue. Please check again

**Pull request closed without merging**
