### PR TITLE
Google Clone

### PR DESCRIPTION
**Pull request by ayan-joshi**
As assigned I added the Google clone in  the frontend projects also added readme file with whole explaination of the google clone @Vikash-8090-Yadav please review my pull request and merge it, will be thankful to you .
SSOC contributor

### CODE REVIEW

**Comment by ayan-joshi** [comment]
@Vikash-8090-Yadav please review it

**Comment by Vikash-8090-Yadav** [comment]
issue no?

**Comment by ayan-joshi** [comment]
@Vikash-8090-Yadav Issue no #241

**Comment by Vikash-8090-Yadav** [comment]
Readme file name should be of .md type not of .txt . plesse correct

**Pull request merged**
