### PR TITLE
BMI calculator

### PR DESCRIPTION
**Pull request by ayan-joshi**
So I added the BMI calculator in the frontend project as I described in the 
issue number #321 
This are the screenshots :-
Screenshot (183)

Screenshot (185)
Screenshot (184)

Please merge my request @Vikash-8090-Yadav

### CODE REVIEW

**Comment by ayan-joshi** [comment]
> Reamde?

should I add readme as a diff file or I add it's detail in the html file

**Comment by shubhisingh184** [comment]
@ayan-joshi Create a separate README.md file for your project, please go through the contribution.md guidelines for the README.md file format. Hope it helps!

**Comment by ayan-joshi** [comment]
@shubhisingh184 added the readme file

**Comment by shubhisingh184** [comment]
@ayan-joshi please add a working video link in README.md file and change Readme.md to README.md

**Comment by ayan-joshi** [comment]
@shubhisingh184 did the changes

**Comment by shubhisingh184** [comment]
@ayan-joshi it would be better if you also attach working video here in conversation section.

**Comment by ayan-joshi** [comment]
> @ayan-joshi it would be better if you also attach working video here in conversation section, after that it will approved soon.

Demo video link 
https://www.loom.com/share/f9432fdd57ad48d694e5dfa7e64a47da?sid=c3845bf7-4eb8-4407-96bb-d48144b6cdff

**Review by shubhisingh184 — APPROVED** [review]

**Review by Vikash-8090-Yadav — CHANGES_REQUESTED** [review]
If your image is not loaded, upload it again and write some description about the picture as well I would suggest including the video in the readme only instead of pasting some other third-party link.

**Comment by ayan-joshi** [comment]
> If your image is not loaded, upload it again and write some description about the picture as well I would suggest including the video in the readme only instead of pasting some other third-party link.

did changes in the readme added the video 
and also uploaded the images

**Review by Vikash-8090-Yadav — APPROVED** [review]
LGTM

**Pull request merged**
