### PR TITLE
[SSoC 2.0] Music Guess Game Done

### PR DESCRIPTION
**Pull request by Avdhesh-Varshney**
Fixes Issue Number - #309 

Title - Music Guessing Game
Tech used - HTML, CSS, and JS

- This is multi player game
- Add more songs in the directory of `songs` and updating the name and path of the song in the script file, makes the game more complex and interesting
- User interface is awesome with cool winning sound
- At the Game Over sound will announce the end of the game

Demo Video
---
https://github.com/Vikash-8090-Yadav/Future.WebNet/assets/114330097/bb08498b-7c31-455a-b8c6-4c4353e5aac6

### CODE REVIEW

**Comment by Avdhesh-Varshney** [comment]
@Vikash-8090-Yadav Sir, please review this pull request and merge it into the main branch of this repository for a successful contribution under SSoC 2.0 program

**Comment by Avdhesh-Varshney** [comment]
@Vikash-8090-Yadav Sir, I have created this pull request 4 days ago, still no action is takes place.
Sir, I requested to review this pull request and merge it into the main branch of this repository for a valuable contribution under SSoC 2.0 program

**Comment by Avdhesh-Varshney** [comment]
@Vikash-8090-Yadav Sir, I have created this pr last week but no action is takes place

I requested to merge this pr for a valuable contribution under SSoC 2.0 program

**Review by shubhisingh184 — APPROVED** [review]

**Review by Vikash-8090-Yadav — APPROVED** [review]
LGTM

**Pull request merged**
