### PR TITLE
Amazon Clone

### LINKED ISSUE #308: Amazon Clone
Project title
Amazon Clone

Project Description
This is an E-COMMERCE website, tech stack to used is HTML, CSS, Js

Doc Domain

- [] Solidity , Html, Css , JavaScript , Web3.js / Ether.js
- [] Solidity , ReactJs /NextJs , Web3.js /Ether.js
- [] Solidity , Python3 , Web3.py
- [] Other , feel free to mention below

#### Are you contributing under any open-source program ? Yes
Amazon clone
<hr/>

### PR DESCRIPTION
**Pull request by TanishqSiva**
closes #308
Kindly review it and then merge it
there were some bugs in previous branch so i closed it and openend new one please check this @Vikash-8090-Yadav sir as soon possible

### CODE REVIEW

**Comment by TanishqSiva** [comment]
> @TanishqSiva bro how can i work on this ??

Raise a new issue for improving or adding cart to my issue's Amazon Clone

**Comment by MohdSultanGit** [comment]
@Vikash-8090-Yadav Sir can you please assign this issue to me as I am ready to work on it

**Comment by Vikash-8090-Yadav** [comment]
Solve the conflict

**Comment by Vikash-8090-Yadav** [comment]
I guess this already merged. Please let me know about this.

**Comment by MohdSultanGit** [comment]
@TanishqSiva bro what's going on here @Vikash-8090-Yadav saying this issue is finished and you're saying to ask him to assign this to me lol I am getting confused .

**Comment by TanishqSiva** [comment]
Sorry, I'm Unable to understand the conflict may i know detailed information on conflict @Vikash-8090-Yadav

**Comment by TanishqSiva** [comment]
i removed the conflict markers and resolved but still it is showing to resolve please give some guidance for it through linkedin or discord @Vikash-8090-Yadav

**Comment by TanishqSiva** [comment]
Okay ill close these PR open a new one

**Comment by TanishqSiva** [comment]
let me close

**Pull request closed without merging**
