### PR TITLE
#355 Digital Clock

### PR DESCRIPTION
**Pull request by Tusharjoshi1703**
#355  I have completed the Digital Clock project.

Screenshot of project
digitalclockscreenshot

https://github.com/Vikash-8090-Yadav/Future.WebNet/assets/103979298/5b88ecb2-0a01-4d05-bbaa-8de7b9df39b6

Recording of project

### CODE REVIEW

**Comment by Tusharjoshi1703** [comment]
@shubhisingh184  I have completed #355  Digital Clock .Please have a look😊

**Review by shubhisingh184 — APPROVED** [review]

**Comment by Tusharjoshi1703** [comment]
@shubhisingh184  Thank you

**Review by Vikash-8090-Yadav — APPROVED** [review]
LGTM

**Review by Vikash-8090-Yadav — APPROVED** [review]
LGTM

**Pull request merged**
