### PR TITLE
Finance tracker project added (issue: 327)

### PR DESCRIPTION
**Pull request by Ahasasjain**
Completed personal finance tracker project please review and merge it to the main branch.

issue: #327

Working video:

https://github.com/Vikash-8090-Yadav/Future.WebNet/assets/101923456/a446b242-e5ca-4d6e-9771-95c6fe2a5a0c

### CODE REVIEW

**Comment by shubhisingh184** [comment]
@Ahasasjain please attach working video here also and do mention the issue no. in the conversation section even if you already mention it in the title, it's a good practice to do it like this. Okay!

**Comment by Ahasasjain** [comment]
@shubhisingh184 I have added the issue number. and the working video is attached in the README file.
please review.

**Comment by shubhisingh184** [comment]
Okay @Ahasasjain great!

**Review by shubhisingh184 — APPROVED** [review]

**Comment by Ahasasjain** [comment]
> Okay @Ahasasjain great!

Thanks

**Review by Vikash-8090-Yadav — APPROVED** [review]
LGTM

**Pull request merged**
