### PR TITLE
Updated file Champs.html in Cricket

### PR DESCRIPTION
**Pull request by ayan-joshi**
As I described in the issue , I updated and improves the champs.html file now it's shows the winner of every Odi , T20 and test world cup champions in the 21st century.
Please look it out and merge my pull request.
I'm a SSOC contributor @Vikash-8090-Yadav

### CODE REVIEW

**Comment by Vikash-8090-Yadav** [comment]
Issue NO ?

**Comment by ayan-joshi** [comment]
Issue number 282 @Vikash-8090-Yadav

**Comment by ayan-joshi** [comment]
@Vikash-8090-Yadav sir please merge the request

**Comment by Vikash-8090-Yadav** [comment]
Thanks!!

**Pull request merged**
