### PR TITLE
Added the To-Do List

### PR DESCRIPTION
**Pull request by rayarka26**
Issue Number #336 
Please add SSOC'23 Labels

### CODE REVIEW

**Comment by rayarka26** [comment]
Screenshot (108)

**Comment by rayarka26** [comment]
Please add SSOC'23 Labels

**Comment by Vikash-8090-Yadav** [comment]
Please make the correct readme. Thanks!

**Comment by rayarka26** [comment]
@Vikash-8090-Yadav  all changes done please check

**Comment by rayarka26** [comment]
Please assign me and add labels of SSOC'23

**Comment by shubhisingh184** [comment]
@rayarka26 Please attach screenshot and working video link in README.md file of your project to follow proper instructions in contributions.md guidelines file. Then, you're good to go!! Okay

**Comment by shubhisingh184** [comment]
@rayarka26 please attach a working video of your project, then it is good to go!!

**Comment by rayarka26** [comment]
https://github.com/Vikash-8090-Yadav/Future.WebNet/assets/74251803/9d210380-0918-4de1-8a29-66f6fb362d66

**Comment by shubhisingh184** [comment]
@rayarka26 Everything looks great, but you just have to update the README.md file in your project. Add the screenshot and video link in that file, after that it will be merged

**Comment by rayarka26** [comment]
@shubhisingh184 done pls check

**Review by shubhisingh184 — APPROVED** [review]

**Review by Vikash-8090-Yadav — APPROVED** [review]
LGTM

**Pull request merged**
