### PR TITLE
Added Weather Forecasting Web- Application

### PR DESCRIPTION
**Pull request by Venerablevivek**
Weathervio: Weather Forecasting Web-Application has been successfully Added to the Level1 Folder.
@Vikash-8090-Yadav Task Done under SSOC'23

### CODE REVIEW

**Comment by Vikash-8090-Yadav** [comment]
Issue NO?

**Comment by Venerablevivek** [comment]
Yesss .... I have successfully solved the issue of adding weather forecasting project ... 
Now, merge this PR ... @Vikash-8090-Yadav

**Comment by Vikash-8090-Yadav** [comment]
Am not seeing any files being added. PLease check once it's showing me empty folder

Screenshot from 2023-06-07 17-07-50

**Comment by Venerablevivek** [comment]
@Vikash-8090-Yadav I have checked... It is not showing now ... 
Wait I will try it again...

**Pull request closed without merging**
