### PR TITLE
Update in Cricket Play

### LINKED ISSUE #247: Inconsistencies in 'Cricket'
Screenshot 2023-06-04 01 07 04

Problems :
1.  Poor UI Interface: The look is not appealing and attractive.
2. Bad Color Theme: The color chosen is not at all tempting.
3. Font family and color issue: Alter font to make the site look better.
4. Better layout and sectioning

There is a need to change the whole design of this website.

### PR DESCRIPTION
**Pull request by bugzzz4u**
Closes #247 

Changed the whole layout and look using HTML and CSS and made further additions to it by adding news box under it.

**Screenshots**
_**Before:**_

Screenshot 2023-06-13 21 51 38

_**After:**_

screenshot png

**Click the following link to see the working video:**

https://github.com/Vikash-8090-Yadav/Future.WebNet/assets/125059410/48206af5-114f-44a6-9111-a2ca84d1e7bf

### CODE REVIEW

**Review by shubhisingh184 — DISMISSED** [review]

**Comment by shubhisingh184** [comment]
@bugzzz4u please upload the working video properly in README.md file.

**Comment by bugzzz4u** [comment]
Done. Can you please check?

**Comment by shubhisingh184** [comment]
@bugzzz4u don't give any hyperlinks for working video, upload the video so that it can be seen directly in README.md file

**Comment by shubhisingh184** [comment]
@bugzzz4u please respond and do the mentioned changes otherwise after 4 days, your contribution will not be counted in SSOC'23.

**Comment by bugzzz4u** [comment]
I have done some modifications. Can you  please check the readme file and let me know?

**Review by shubhisingh184 — APPROVED** [review]

**Review by Vikash-8090-Yadav — APPROVED** [review]
LGTM

**Pull request merged**
