### PR TITLE
Snake Game added

### LINKED ISSUE #346: Snake game
### Project title
 Snake game 

### Project Description
Hi @Vikash-8090-Yadav , I want to add a snake game . it is very interesting game and it is a web game made using HTML , CSS JAVASCRIPT . 
Please assign it to me .
My branch will be Adityamishra9719

It will look like below image :-
Screenshot 2023-06-20 200425

### Doc Domain

- [] Solidity , Html, Css , JavaScript , Web3.js / Ether.js
- [] Solidity , ReactJs /NextJs , Web3.js /Ether.js
- [] Solidity , Python3 , Web3.py
- [] Other , feel free to mention below

#### Are you contributing under any open-source program ?
Yes , in  GSsoc'23 .
<hr/>

### PR DESCRIPTION
**Pull request by Adityamishra9719**
I had added a game name Anaconda a snake game .
It is made using HTML , CSS and JAVASCRIPT .
It is very easy to play as you only have to use up , down, left and right arrow to move snake for eating food and making high scores .
Fixes #346 
The game look like the below screenshot -
Anaconda_Snake_game

Working video of game -:

https://github.com/Vikash-8090-Yadav/Future.WebNet/assets/105539123/d0927bad-4bba-4975-b66a-4b8715398ef2

 
My Branche name is Adityamishra9719
Thank you

### CODE REVIEW

**Comment by shubhisingh184** [comment]
@Adityamishra9719 please attach a working video of this game.

**Comment by Adityamishra9719** [comment]
Okk

**Comment by Adityamishra9719** [comment]
@shubhisingh184 game video is attached .

**Comment by shubhisingh184** [comment]
@Adityamishra9719 The video is fine, but you have to add README.md file in your project, to add this file please follow the contributions.md guidelines and the README.md file format, then this is good to go!!!

**Comment by Adityamishra9719** [comment]
README.md file added !

**Comment by Vikash-8090-Yadav** [comment]
@Adityamishra9719 Please attach the running  video.

**Comment by Adityamishra9719** [comment]
working video added in README.md file  and in pr too.

**Comment by shubhisingh184** [comment]
@Adityamishra9719 yes, the README.md file is fine now. Thankyou for your contribution!

**Review by shubhisingh184 — APPROVED** [review]

**Review by Vikash-8090-Yadav — APPROVED** [review]
LGTM

**Pull request merged**
