### PR TITLE
initial commit which closes #372

### LINKED ISSUE #372: [SSOC 2.0] Frontend Project Mi Store Clone
### Project title
Mi Store Clone

### Project Description
This is a frontend project in which Mi-Store Clone has been made

### Doc Domain

- [] Solidity , Html, Css , JavaScript , Web3.js / Ether.js
- [] Solidity , ReactJs /NextJs , Web3.js /Ether.js
- [] Solidity , Python3 , Web3.py
- [] Other , feel free to mention below

#### Are you contributing under any open-source program ?
  [SSOC 2.0]
Screenshot (54)

<hr/>

### PR DESCRIPTION
**Pull request by akshatmishra25**
Screenshot (54)
This is a Frontend MI Store Clone Project. 
The Project has been added to the Frontend Projects directory with the name mi-store. 
This PR thus will close in the following issue - [SSOC 2.0] Frontend Project Mi Store Clone #372.

### CODE REVIEW

**Comment by shubhisingh184** [comment]
@akshatmishra25 please provide proper description of pull request along with issue number.

**Comment by akshatmishra25** [comment]
> @akshatmishra25 please provide proper description of pull request along with issue number.

Thanks for your response I have updated the PR.

**Comment by shubhisingh184** [comment]
@akshatmishra25 there is no files in the specified way, is this the zip folder? If yes or any other folder, then please change it to files format like index.html, style.css etc and don't forget to include README.md file. If you're facing any kind of problem during pushing code, the let me know on discord, I'll help you out. Okay!!

**Comment by shubhisingh184** [comment]
@akshatmishra25 If you want to contribute your project under SSOC'23 then you should complete it ASAP.

**Pull request closed without merging**
