### PR TITLE
Task Manager web application 

### PR DESCRIPTION
**Pull request by NupurHardiya**
Implemented Task Manager web application with HTML, CSS, and JavaScript, enabling users to create, organize, and prioritize tasks. The application includes features such as task categorization, due date reminders, and a user-friendly interface for seamless task management. This commit contributes to the development of a valuable tool for efficient task tracking and enhances user productivity.
[Issue no. - #287 ]

### CODE REVIEW

**Comment by shubhisingh184** [comment]
@NupurHardiya please specify the issue number.

**Comment by NupurHardiya** [comment]
Issue no. #284

**Comment by NupurHardiya** [comment]
Hello Shubhi

Issue no. is #284

**Comment by NupurHardiya** [comment]
https://github.com/Vikash-8090-Yadav/Future.WebNet/assets/113535580/ca53f7e6-e043-4543-b1ed-ac6c90ea64c9

**Review by Vikash-8090-Yadav — APPROVED** [review]
LGTM

**Comment by shubhisingh184** [comment]
@NupurHardiya You should put your project under "Front-end projects" folder. Please do these changes ASAP.

**Pull request merged**
