### PR TITLE
added a concept of  API's

### PR DESCRIPTION
**Pull request by liza-bhutani**
added a blog on APIs , what is APIs , how it works and what are its types.

### CODE REVIEW

**Comment by Vikash-8090-Yadav** [comment]
Hey are u a contributor  from the SSOC  ?

**Comment by liza-bhutani** [comment]
> Hey are u a contributor  from the SSOC  ? 

No😅

**Comment by Vikash-8090-Yadav** [comment]
If possible please tell me about the pr description and what have u done. It's good practice. Thank uh!

**Comment by liza-bhutani** [comment]
> Hey are u a contributor  from the SSOC  ? 

Yes want to contribute into it ..

**Comment by liza-bhutani** [comment]
> If possible please tell me about the pr description and what have u done. It's good practice. Thank uh! 

Yeah!! I have added description

**Comment by Vikash-8090-Yadav** [comment]
> > Hey are u a contributor  from the SSOC  ?
> 
> Yes want to contribute into it ..

if you are contributing under ssoc , then this pr will count for the ssoc as the programme havem't yet started. 
Let me know if u want me to review and merge this pr .
Thanks!

**Comment by liza-bhutani** [comment]
> > > Hey are u a contributor  from the SSOC  ?
> > 
> > Yes want to contribute into it ..
> 
> if you are contributing under ssoc , then this pr will count for the ssoc as the programme havem't yet started. 
> Let me know if u want me to review and merge this pr .
> Thanks!  

Yes Review my PR.

**Comment by Vikash-8090-Yadav** [comment]
Change the folder , keep this in blog folder and the file convention should be Api.md

**Pull request closed without merging**
