### PR TITLE
To do task

### PR DESCRIPTION
**Pull request by VardaPanchal005**
This full stack website is made with the help of Truffle , next js and Solidity. Whenever u write  a task after  authorization through metmask the task will be added or deleted after refreshing the page.

issue:#226

@shubhisingh184 please review my pr

### CODE REVIEW

**Comment by VardaPanchal005** [comment]
please review my pr soon as there are not many days left  @shubhisingh184

**Comment by Vikash-8090-Yadav** [comment]
> > @VardaPanchal005 Maybe your forked repo is much pulls behind( it means many projects are added after you forked the repo so you should fetch the changes from the original repo itself) please sync these changes first and then create a pull request.
> 
> please check it now

still the same issue.

**Comment by VardaPanchal005** [comment]
> > > @VardaPanchal005 Maybe your forked repo is much pulls behind( it means many projects are added after you forked the repo so you should fetch the changes from the original repo itself) please sync these changes first and then create a pull request.
> > 
> > 
> > please check it now
> 
> still the same issue.

I will update it now but please check it soon otherwise same problem will happen again

**Comment by VardaPanchal005** [comment]
> > > @VardaPanchal005 Maybe your forked repo is much pulls behind( it means many projects are added after you forked the repo so you should fetch the changes from the original repo itself) please sync these changes first and then create a pull request.
> > 
> > 
> > please check it now
> 
> still the same issue.

Can you check now as it shows up to date in mine

**Comment by VardaPanchal005** [comment]
Screenshot 2023-07-27 225803

**Comment by MisterMickey** [comment]
@VardaPanchal005 Tumne jin bhi files me change kiya hai unko copy karke pc me dusre location pe store karlo fir GH desktop se tumhari forked repo me jake **sync fork** karo and then tumhari cloned repo directory me jake **git stash** command run karo and then **git pull**, isse tumhari cloned repo original repo ke sath sync ho jayegi iske bad tumne jo files extra add ki thi unhe firse copy paste kardo and lastly koi aur change kiya ho to use bhi update karo and push changes.

**Comment by VardaPanchal005** [comment]
> @VardaPanchal005 Tumne jin bhi files me change kiya hai unko copy karke pc me dusre location pe store karlo fir GH desktop se tumhari forked repo me jake **sync fork** karo and then tumhari cloned repo directory me jake **git stash** command run karo and then **git pull**, isse tumhari cloned repo original repo ke sath sync ho jayegi iske bad tumne jo files extra add ki thi unhe firse copy paste kardo and lastly koi aur change kiya ho to use bhi update karo and push changes.

what is wrong with my current method

**Comment by MisterMickey** [comment]
Probably your forked repo is behind the main repo @VardaPanchal005

**Comment by MisterMickey** [comment]
@VardaPanchal005 Then cloned one is not synced with forked one, pull is required maybe.

**Comment by VardaPanchal005** [comment]
> Screenshot 2023-07-27 225803
> @Vikash-8090-Yadav

.... @MisterMickey

**Comment by shubhisingh184** [comment]
@VardaPanchal005 please dm me  on discord, if you're still facing the similar issue.

**Comment by VardaPanchal005** [comment]
> @VardaPanchal005 please dm me on discord, if you're still facing the similar issue.

okay. check your discord

**Comment by Vikash-8090-Yadav** [comment]
> > Screenshot 2023-07-27 225803
> > @Vikash-8090-Yadav
> 
> .... @MisterMickey 

have u done git pull ?

**Comment by VardaPanchal005** [comment]
> > > Screenshot 2023-07-27 225803
> > > @Vikash-8090-Yadav
> > 
> > 
> > .... @MisterMickey
> 
> have u done git pull ?

Up to date

**Pull request closed without merging**
